[metadata]
name = 8051-simulator
version = 1.0.0
license = MIT
author = Utkarsh Gupta
author_email = utkarshgupta7714@gmail.com
description = Web-based 8051 microcontroller simulator with real-time execution and visualization
long_description = file: README.md
long_description_content_type = text/markdown

[options]
zip_safe = False
packages = find:
python_requires = >=3.7

install_requires =
    flask
    rich
    gunicorn

[options.packages.find]
exclude =
    tests

[flake8]
ignore = E203
max-line-length = 120

[isort]
balanced_wrapping = True
default_section = THIRDPARTY
length_sort = False
length_sort_sections = stdlib
line_length = 120
multi_line_output = 3
no_lines_before = LOCALFOLDER
sections = STDLIB, THIRDPARTY, FIRSTPARTY, LOCALFOLDER